/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.centrale.objet.WoE;

import java.util.Random;
import java.util.ArrayList;
import java.util.List;

/**
 * The class {@link org.centrale.objet.WoE.World} represents a world that
 * contains different roles like
 * {@code Personnage}({@code Archer},{@code Paysan}, {@code Guerrier}) and
 * {@code Monstre}({@code Lapin}, {@code Loup}), the role {@link Personnage} can
 * attack {@link Monstre} through the method
 * {@link org.centrale.objet.WoE.Guerrier#combattre(org.centrale.objet.WoE.Creature) combattre},
 * it can also restore vitality through the use of {@code PationSoin}.
 *
 * @author wuzilong
 * @author ZouKang
 * @version 1.0
 */
public class World {

    /**
     * the size of the World : TAILLE x TAILLE
     */
    private final static int TAILLE = 50;

    /**
     * to identify if a coordinate is occupied, 0 stands for free
     * original point is [0,0] 
     * X coordinate [0,TAILLE]
     * Y coordinate [0,TAILLE]
     */
    private static final int[][] OCCUPIED = new int[TAILLE+1][TAILLE+1];
    
    /**
     * 
     * @param x x-coordinate of the World
     * @param y y-coordinate of the World
     * @return the state of this position[x,y]
     */
    public static int getOCCUPIED(int x, int y){
        return OCCUPIED[x][y];
    }
    
    /**
     * 
     * @param x x-coordinate of the World
     * @param y y-coordinate of the World
     * @param state 0 or 1;
     *              0:free
     *              1:occupied
     */
    public static void setOCCUPIED(int x, int y,int state){
        OCCUPIED[x][y] = state;
    }
    
    /**
     * Representing an {@code Archer}({@code Personnage}) in the world
     */
    public Archer robin;
    /**
     * Representing a Paysan(Personnage) in the world
     */
    public Paysan peon;
    /**
     * Representing a Lain(Monstre) in the world
     */
    public Lapin bugs1;
    /**
     * Representing another Lapin(Monstre) in the world
     */
    public Lapin bugs2; //new attribute
    /**
     * Representing an Archer(Personnage) in the world
     */
    public Archer guillaumeT;
    /**
     * Representing a Guerrier(Personnage) in the world
     */
    public Guerrier grosBill;//new
    /**
     * Representing a Loup(Monstre) in the world
     */
    public Loup wolfie;//new

    public ArrayList<Creature> creatures =new ArrayList<>();
    

    
   /**
     * Default parameterless constructor
     */
 
    public World(){
  
    }
    
    
    /**
     *
     */
    public void tourDeJeu() {

    }

    public void aficheWorld() {

    }


    
    /**
     * Generate a random world with the coordinates of the Creature randomly
     * generated by {@link java.util.Random}
     */
    public void creerMondeAlea() {

        Random generateurAleatoire = new Random(100);
        int nbArchers = generateurAleatoire.nextInt(100);
        for (int i = 0; i < nbArchers; i++) {
            Archer a = new Archer(createPoints());
            creatures.add(a);
        }
        
        int nbPaysan = generateurAleatoire.nextInt(100);
        for (int i = 0; i < nbPaysan; i++) {
            Paysan a = new Paysan(createPoints());
            creatures.add(a);
        }
        
        int nbLapin = generateurAleatoire.nextInt(100);
        for (int i = 0; i < nbLapin; i++) {
            Lapin a = new Lapin(createPoints());
            creatures.add(a);
        }

        int nbGuerrier = generateurAleatoire.nextInt(100);
        for (int i = 0; i < nbGuerrier; i++) {
            Guerrier a = new Guerrier(createPoints());
            creatures.add(a);
        }

        int nbLoup = generateurAleatoire.nextInt(100);
        for (int i = 0; i < nbLoup; i++) {
            Loup a = new Loup(createPoints());
            creatures.add(a);
        }
        
        System.out.println("nbArcher: " + nbArchers);
        for (Creature i : creatures){
            i.affiche();
        }
        
        
        long debut = System.currentTimeMillis();
 
        int sumPtVie =  0;
        for(int i =0;i<creatures.size();i++){
            sumPtVie+=creatures.get(i).getPtVie();
        }
        long fin = System.currentTimeMillis();
        System.out.println("temps ecoule en ms : " + (fin - debut));
        
        
        System.out.println("sumPtVie: " + sumPtVie);
        
        System.out.println("=============test deplacement: =============");
        System.out.println("position now:");
        creatures.get(0).affiche();
        System.out.print("table OCCUPIED now: ");
        System.out.println(OCCUPIED[creatures.get(0).getPos().getX()][creatures.get(0).getPos().getY()]);
        System.out.print("table OCCUPIED to move: ");
        System.out.println(OCCUPIED[creatures.get(0).getPos().getX()+1][creatures.get(0).getPos().getY()+1]);
        
        creatures.get(1).setPos(new Point2D(creatures.get(0).getPos().getX()+1,creatures.get(0).getPos().getY()));
        setOCCUPIED(creatures.get(0).getPos().getX()+1,creatures.get(0).getPos().getY(),1);
        creatures.get(2).setPos(new Point2D(creatures.get(0).getPos().getX()+1,creatures.get(0).getPos().getY()-1));
        setOCCUPIED(creatures.get(0).getPos().getX()+1,creatures.get(0).getPos().getY()-1,1);
        creatures.get(3).setPos(new Point2D(creatures.get(0).getPos().getX(),creatures.get(0).getPos().getY()-1));
        setOCCUPIED(creatures.get(0).getPos().getX(),creatures.get(0).getPos().getY()-1,1);
        creatures.get(4).setPos(new Point2D(creatures.get(0).getPos().getX()-1,creatures.get(0).getPos().getY()-1));
        setOCCUPIED(creatures.get(0).getPos().getX()-1,creatures.get(0).getPos().getY()-1,1);
        creatures.get(5).setPos(new Point2D(creatures.get(0).getPos().getX()-1,creatures.get(0).getPos().getY()));
         setOCCUPIED(creatures.get(0).getPos().getX()-1,creatures.get(0).getPos().getY(),1);
        creatures.get(6).setPos(new Point2D(creatures.get(0).getPos().getX()-1,creatures.get(0).getPos().getY()+1));
        setOCCUPIED(creatures.get(0).getPos().getX()-1,creatures.get(0).getPos().getY()+1,1);
        creatures.get(7).setPos(new Point2D(creatures.get(0).getPos().getX(),creatures.get(0).getPos().getY()+1));
         setOCCUPIED(creatures.get(0).getPos().getX(),creatures.get(0).getPos().getY()+1,1);
         
        creatures.get(0).deplace();
        
        System.out.print("table OCCUPIED original: ");
        System.out.println(OCCUPIED[creatures.get(0).getPos().getX()-1][creatures.get(0).getPos().getY()-1]);
        System.out.print("table OCCUPIED now: ");
        System.out.println(OCCUPIED[creatures.get(0).getPos().getX()][creatures.get(0).getPos().getY()]);
        System.out.println("position after:");
        creatures.get(0).affiche();
        
        
        /* TP3 test
        //create some roles
        bugs1 = new Lapin();
        bugs2 = new Lapin();

        robin = new Archer("robin");
        peon = new Paysan("peon");

        grosBill = new Guerrier("grosBill");

        wolfie = new Loup();

       
        
        robin.setPos(points[0]);
        peon.setPos(points[1]);
        bugs1.setPos(points[2]);
        bugs2.setPos(points[3]);
        grosBill.setPos(points[4]);
        wolfie.setPos(points[5]);
        
        //copie
        System.out.println("================test copie================");
        guillaumeT = new Archer(robin);
        guillaumeT.setNom("guillaumeT");
        System.out.println("--------------avant-------------");
        guillaumeT.affiche();
        robin.affiche();
        System.out.println("--------------apres-------------");
        robin.deplace();
        guillaumeT.affiche();
        robin.affiche();
        System.out.println("================fin copie================");
        //Test potion function
        System.out.println("================test potion================");
        robin.setPtVie(70);
        PotionSoin potion1 = new PotionSoin();
        PotionSoin potion2 = new PotionSoin();
        robin.getPotionsoin().add(potion1);
        robin.getPotionsoin().add(potion2);
        robin.affiche();
        System.out.println("nombre de potion de robin: " + robin.getPotionsoin().size());
        System.out.println("consumer 1 potion");
        robin.usagePotion(potion2);
        robin.affiche();
        System.out.println("nombre de potion de robin: " + robin.getPotionsoin().size());
        System.out.println("consumer 1 potion");
        robin.usagePotion(potion1);
        System.out.println("nombre de potion de robin: " + robin.getPotionsoin().size());
        robin.usagePotion(potion1);
        robin.affiche();
        System.out.println("================fin de test potion================");
         */
    }

    /**
     * generate a random Point2D
     *
     * @return a instance of Class Point2D which generated by random
     */
    public Point2D createPoints() {
        Random generateurAleatoire = new Random();
        int X;
        int Y;
        while (true) {
            X = generateurAleatoire.nextInt(TAILLE + 1);
            Y = generateurAleatoire.nextInt(TAILLE + 1);
            if (OCCUPIED[X][Y] == 0) {
                OCCUPIED[X][Y] = 1;
                break;
            }
        }
        return new Point2D(X, Y);

    }

}
